services:
  db:
    image: mysql:8.0
    container_name: hubfy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hubfy
      MYSQL_USER: hubfy
      MYSQL_PASSWORD: hubfy123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hubfy-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hubfy-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - hubfy-network

networks:
  hubfy-network:

volumes:
  mysql_data:
